### ISSUE TITLE
Works on Options Pages ?

### ISSUE THREAD

**Issue by alexis-magina** [dThemeStudio/cmb2-tabs#1]
Hello,

Is this works on custom options pages ?
I just downloaded it, and works perfect on posts & pages edit, but I can't make it work on custom options pages.
I used this snippet from CMB2 to declare my optionPage : https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php 

The fields are well displayed on tabs, but they are not saved in options

**Comment by kuzmenko1256** [comment]
Hello.
We have added support for the "options page"
Enable "settings page" you must add the string `'object_type' => 'options-page',` in your theme-option-cmd.php file.

## Example
<pre>`
$box_options = array(
	'id'         => $this->metabox_id,
	'hookup'     => false,
	'cmb_styles' => false,
	'object_type' => 'options-page',
	'show_on'    => array(
		// These are important, don't remove
		'key'   => 'options-page',
		'value' => array( $this->key, )
	),
);
$cmb = new_cmb2_box( $box_options );
`</pre>

**Comment by alexis-magina** [comment]
Thanks, it works well :-)
