### ISSUE TITLE
Default Data and Blank Data Not Showing or Saving

### ISSUE THREAD

**Issue by glennlaysonjr** [dThemeStudio/cmb2-tabs#15]
When you remove saved data it wont go back to the default data in any field or color field via the cmb2  'default'          => 'default text' .... I also have the same problem when i remove a image if I don't add a new image instead of showing blank it shoes the last saved image again. I had all this working before so I know its not an CMB2 issue. It started after I loaded the plugin. 

Is there a fix for this? I have to give the plugin over to my client next week?

**Comment by kuzmenko1256** [comment]
The default data does not work in the metabox or on the option page?
What version of CMB2 are you using?

**Comment by glennlaysonjr** [comment]
With your last update yesterday it works great now thanks!

G
