### ISSUE TITLE
In compatibility with CMB2-conditionals

### ISSUE THREAD

**Issue by xlplugins** [dThemeStudio/cmb2-tabs#4]
HI,

I have the settings in which I have the conditional logic set on tabs, they should only show when checkbox is checked. 

I figured out that CMB2-conditionals adds data attribute to the field that needs conditional visibility. 

When I add attributes like this,

   array(
                'id' => 'tabs__',
                'type' => 'tabs',
                'tabs' => apply_filters('wcst_modify_field_config_products', $tabs_setting),
                'attributes' => array(
                    'data-conditional-id' => 'wcst_override_global_settings',

                ),

            )

But attribute was not adding to the field wrapper. 

So I modified the CMB2_Tabs's render function and adds attribute to the wrapper. 

like this, 

	$attrs = $field_object->args['attributes'];
		$attributes = '';
		foreach ( $attrs as $attr => $val ) {
			// if data attribute, use single quote wraps, else double
			$quotes = false !== stripos( $attr, 'data-' ) ? "'" : '"';
			$attributes .= sprintf( ' %1$s=%3$s%2$s%3$s', $attr, $val, $quotes );
		}

& calls `$attributes` to the the wrapper like 
`<div class="dtheme-cmb2-tabs" <?php echo $attributes; ?>>`

Now this functionality works. 

I bundled in in a plugin, so I need to ensure that my code runs for the tabs. 

Could you tell me the way how I can ensure that my changes always runs.  

Also, I think it would be great if you add attrubites support to your code. 

Thanks!

**Comment by kuzmenko1256** [comment]
Hi,
The update v 1.2.1: added support for custom attributes for the tabs container.
Example:
<pre>
$cmb->add_field( array(
	'id'   => '__tabs',
	'type' => 'tabs',
	'attributes' => array(
		'data-conditional-id' => 'wcst_override_global_settings'
	),
	'tabs' => $tabs_setting
) );
</pre>
