### ISSUE TITLE
wysiwyg field not respecting textarea_rows option

### ISSUE THREAD

**Issue by noquierouser** [dThemeStudio/cmb2-tabs#5]
How to replicate bug:

1. Set many tabs, each with a `wysiwyg` field with the `textarea_rows` option set to any value
2. Go to Dashboard and check the metabox and its tabs

Expected behavior:
Any `wysiwyg` field should respect the value set in `textarea_rows` option.

Actual behavior:
Only `wysiwyg` set in the first tab respects the value in `textarea_rows`. In subsequent tabs the value has no effect.

**Comment by kuzmenko1256** [comment]
#7

**Comment by kuzmenko1256** [comment]
Fixed display error height wysiwyg field #7
